# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\"?\n\x15UpdateTaskNameRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x15\n\rnew_task_name\x18\x02 \x01(\t\">\n\x17UpdateTaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nnew_status\x18\x02 \x01(\t\"B\n\x11\x43reateTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"$\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x11\n\x0fListTaskRequest\"!\n\x0eGetTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"0\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xfa\x02\n\x0bTaskService\x12\x41\n\x0eUpdateTaskName\x12\x1b.task.UpdateTaskNameRequest\x1a\x12.task.TaskResponse\x12\x45\n\x10UpdateTaskStatus\x12\x1d.task.UpdateTaskStatusRequest\x1a\x12.task.TaskResponse\x12\x39\n\nCreateTask\x12\x17.task.CreateTaskRequest\x1a\x12.task.TaskResponse\x12\x39\n\nDeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x12.task.TaskResponse\x12\x36\n\tListTasks\x12\x15.task.ListTaskRequest\x1a\x12.task.TaskResponse\x12\x33\n\x07GetTask\x12\x14.task.GetTaskRequest\x1a\x12.task.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATETASKNAMEREQUEST']._serialized_start=20
  _globals['_UPDATETASKNAMEREQUEST']._serialized_end=83
  _globals['_UPDATETASKSTATUSREQUEST']._serialized_start=85
  _globals['_UPDATETASKSTATUSREQUEST']._serialized_end=147
  _globals['_CREATETASKREQUEST']._serialized_start=149
  _globals['_CREATETASKREQUEST']._serialized_end=215
  _globals['_DELETETASKREQUEST']._serialized_start=217
  _globals['_DELETETASKREQUEST']._serialized_end=253
  _globals['_LISTTASKREQUEST']._serialized_start=255
  _globals['_LISTTASKREQUEST']._serialized_end=272
  _globals['_GETTASKREQUEST']._serialized_start=274
  _globals['_GETTASKREQUEST']._serialized_end=307
  _globals['_TASKRESPONSE']._serialized_start=309
  _globals['_TASKRESPONSE']._serialized_end=357
  _globals['_TASKSERVICE']._serialized_start=360
  _globals['_TASKSERVICE']._serialized_end=738
# @@protoc_insertion_point(module_scope)
